# Generated by Django 5.1.6 on 2025-02-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('assunto', models.TextField(max_length=200)),
                ('prazo', models.DateField(max_length=100)),
                ('status', models.CharField(default='Em andamento', max_length=50)),
            ],
        ),
    ]
