# Generated by Django 5.1.6 on 2025-02-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=10)),
            ],
        ),
    ]
