# Generated by Django 5.1.6 on 2025-02-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrganizeMe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='status',
        ),
        migrations.AddField(
            model_name='atividade',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='prazo',
            field=models.DateField(),
        ),
    ]
